name: lesion_detector
description: A Flutter app capable of detecting skin cancer lesions using Computer Vision.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  camera: ^0.8.1
  # adding tflite from Github for now, since the pub version contains a bug for Android
  # versions <= 6.0, see https://github.com/shaqian/flutter_tflite/issues/165, could be reverted
  # once the new version is available officially
  tflite:
    git:
      url: https://github.com/shaqian/flutter_tflite.git
      ref: master

flutter:
  uses-material-design: true

  assets:
    - assets/
